apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fmovil-microservices
  labels:
    app: fmovil-microservices
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fmovil-microservices
      component: frontend
  template:
    metadata:
      labels:
        app: fmovil-microservices
        component: frontend
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: frontend
        image: harbor.oefa.gob.pe/fmovil/hectorvc2022/fmovil-frontend:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          name: http
          protocol: TCP
        env:
        - name: API_BASE_URL
          value: "https://gateway-route-fmovil.apps.okd-dev.oefa.gob.pe"
        - name: FRONTEND_BASE_URL
          value: "https://oefa-front.apps.okd-dev.oefa.gob.pe"
        - name: APP_NAME
          value: "OEFA - Sistema de Firmas Digitales"
        - name: APP_VERSION
          value: "v1.0.0"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30